### ISSUE TITLE
2-Factor Authentication

### ISSUE THREAD

**Issue by Sebastian-git** [clayshieh/FMF_Server#5]
I'm receiving the following error and assume it's because my account has two-factor authentication which results in self.contacts being null:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    f.get_user_by_name("Bay")
  File "/Users/sebastiancevallos/Desktop/cs/programs/icloud/FMF.py", line 270, in get_user_by_name
    if user in self.contacts:
TypeError: argument of type 'NoneType' is not iterable

I went back and printed out the value of self.contacts, which was "None". Let me know if there are currently measures in place for 2-Factor Authentication similar to pyicloud (https://github.com/picklepete/pyicloud) or if you would like to collaborate to find a solution.

Thanks,
Sebastian

**Comment by clayshieh** [comment]
I've added another repo that implements 2FA which uou can take a look here: https://github.com/clayshieh/icloud

I will refactor FMF_server to use that as well as other changes

refer to #1

**Comment by clayshieh** [comment]
I've implemented 2FA here: https://github.com/clayshieh/icloud but that code currently only handles accounts with 2FA. I need to figure out a way to handle accounts without 2FA but I will be refactoring the FMF_Server code soon to use the new icloud library!
